/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : localhost
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : CJH

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-05-30 17:05:45
*/


-- ----------------------------
-- Table structure for PAYMENT_CODE
-- ----------------------------
DROP TABLE "CJH"."PAYMENT_CODE";
CREATE TABLE "CJH"."PAYMENT_CODE" (
"CODE_ID" NUMBER(10) NOT NULL ,
"FIRSTARR" VARCHAR2(100 BYTE) NOT NULL ,
"SECONDARR" VARCHAR2(100 BYTE) NOT NULL ,
"ENCODE_T" BLOB NOT NULL ,
"DECODE_T" BLOB NOT NULL ,
"SECRETKEY" BLOB NOT NULL ,
"LAST_UPDATE" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."CODE_ID" IS 'ID';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."FIRSTARR" IS '第一个移位符';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."SECONDARR" IS '第二个移位符';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."ENCODE_T" IS '第一号码表';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."DECODE_T" IS '第二号码表';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."SECRETKEY" IS '加解密随机数';
COMMENT ON COLUMN "CJH"."PAYMENT_CODE"."LAST_UPDATE" IS '最后更新时间';

-- ----------------------------
-- Table structure for PAYMENT_TOKEN_USER
-- ----------------------------
DROP TABLE "CJH"."PAYMENT_TOKEN_USER";
CREATE TABLE "CJH"."PAYMENT_TOKEN_USER" (
"ID" NUMBER(19) NOT NULL ,
"USER_ID" VARCHAR2(20 BYTE) NOT NULL ,
"TOKEN" VARCHAR2(50 BYTE) NOT NULL ,
"LAST_UPDATE" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "CJH"."PAYMENT_TOKEN_USER"."ID" IS '自增ID';

-- ----------------------------
-- Checks structure for table PAYMENT_CODE
-- ----------------------------
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("CODE_ID" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("FIRSTARR" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("SECONDARR" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("ENCODE_T" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("DECODE_T" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("SECRETKEY" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_CODE" ADD CHECK ("LAST_UPDATE" IS NOT NULL);

-- ----------------------------
-- Checks structure for table PAYMENT_TOKEN_USER
-- ----------------------------
ALTER TABLE "CJH"."PAYMENT_TOKEN_USER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_TOKEN_USER" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_TOKEN_USER" ADD CHECK ("TOKEN" IS NOT NULL);
ALTER TABLE "CJH"."PAYMENT_TOKEN_USER" ADD CHECK ("LAST_UPDATE" IS NOT NULL);
